#!/usr/bin/env bash
# Put HTTPS in front of the bots so the PREBUILT BROWSER CLIENT (/client) works from a phone.
#
# WHY THIS EXISTS
# The runner's prebuilt UI is a browser mic app: it calls navigator.mediaDevices.getUserMedia.
# Browsers only expose mediaDevices on a SECURE CONTEXT (https, or localhost). Served from
# http://<droplet-ip>:8080/client it fails silently — the bundle has no isSecureContext guard,
# so the page just sits there "loading" forever. /status still answers, which makes it look
# like a network problem. It isn't: it's the origin.
#
# WHAT THIS DOES
#   1. Gets a real Let's Encrypt cert WITHOUT owning a domain, via sslip.io wildcard DNS
#      (nova.<ip>.sslip.io resolves to <ip>, so HTTP-01 just works).
#   2. Reverse-proxies https://nova.<ip>.sslip.io  -> 127.0.0.1:8080  (Nova)
#                       https://kaira.<ip>.sslip.io -> 127.0.0.1:8081  (Kaira)
#   3. Injects the `x-bot-token` header upstream, because the browser client can't send it —
#      so /api/offer stops 403ing without weakening the bot.
#   4. Puts HTTP basic auth in front, since the injected token would otherwise make the bots
#      open to anyone who guesses the hostname.
#
# It is ADDITIVE: it does not touch, rebuild, or restart the running containers, and the
# plain-HTTP :8080/:8081 endpoints the native app uses keep working exactly as before.
#
#   bash tls-setup.sh                 # password auto-generated and printed
#   WEB_PASSWORD=hunter2 bash tls-setup.sh
#
set -euo pipefail

ENV_FILE=${ENV_FILE:-/opt/voidai/.env}
CADDYFILE=${CADDYFILE:-/etc/caddy/Caddyfile}
WEB_USER=${WEB_USER:-void}
NOVA_PORT=${NOVA_PORT:-8080}
KAIRA_PORT=${KAIRA_PORT:-8081}

# --- Public IP (sslip.io encodes it in the hostname, so this must be the real one) ---
IP=${DROPLET_IP:-}
if [ -z "$IP" ]; then
    for svc in ifconfig.me api.ipify.org icanhazip.com; do
        IP=$(curl -fsS --max-time 10 "https://$svc" 2>/dev/null | tr -d '[:space:]') || IP=""
        [ -n "$IP" ] && break
    done
fi
if ! printf '%s' "$IP" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$'; then
    echo "Could not determine the public IPv4. Re-run with: DROPLET_IP=<ip> bash $0" >&2
    exit 1
fi
NOVA_HOST="nova.$IP.sslip.io"
KAIRA_HOST="kaira.$IP.sslip.io"

# --- The bots' shared token, so Caddy can present it on the browser's behalf ---
BOT_TOKEN=""
if [ -f "$ENV_FILE" ]; then
    # Last assignment wins (same as dotenv), minus surrounding quotes and any CRLF.
    BOT_TOKEN=$(sed -n 's/^[[:space:]]*BOT_AUTH_TOKEN[[:space:]]*=[[:space:]]*//p' "$ENV_FILE" \
        | tail -1 | tr -d '\r' | sed -e 's/^"//' -e 's/"$//' -e "s/^'//" -e "s/'\$//")
fi
if [ -n "$BOT_TOKEN" ]; then
    echo "==> Found BOT_AUTH_TOKEN in $ENV_FILE — Caddy will inject it upstream"
else
    echo "==> No BOT_AUTH_TOKEN in $ENV_FILE — assuming the bots are unauthenticated"
fi

WEB_PASSWORD=${WEB_PASSWORD:-$(head -c 18 /dev/urandom | base64 | tr -d '/+=' | head -c 20)}

# --- Firewall: ACME HTTP-01 needs :80, the browser needs :443 ---
# Media is unchanged — it stays on the already-open 10000:65535/udp range, direct to aiortc.
if command -v ufw >/dev/null 2>&1; then
    ufw allow 80/tcp
    ufw allow 443/tcp
fi

# --- Caddy (host install, not docker: the bots run --network host on loopback) ---
if ! command -v caddy >/dev/null 2>&1; then
    echo "==> Installing Caddy"
    apt-get update -qq
    apt-get install -y -qq debian-keyring debian-archive-keyring apt-transport-https curl gnupg
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' \
        | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' \
        | tee /etc/apt/sources.list.d/caddy-stable.list >/dev/null
    apt-get update -qq
    apt-get install -y -qq caddy
fi

PW_HASH=$(caddy hash-password --plaintext "$WEB_PASSWORD")

# --- Caddyfile ---
# `basic_auth` is the Caddy >=2.8 spelling; older builds want `basicauth`. Emit the modern
# one and fall back only if validation rejects it, so this works on whatever apt ships.
write_caddyfile() {
    local auth_directive=$1
    local token_line=""
    [ -n "$BOT_TOKEN" ] && token_line="        header_up x-bot-token \"$BOT_TOKEN\""

    cat >"$CADDYFILE" <<EOF
# Generated by pipecat-agent/deploy/tls-setup.sh — regenerate rather than hand-editing.

$NOVA_HOST {
    $auth_directive {
        $WEB_USER $PW_HASH
    }
    reverse_proxy 127.0.0.1:$NOVA_PORT {
$token_line
    }
}

$KAIRA_HOST {
    $auth_directive {
        $WEB_USER $PW_HASH
    }
    reverse_proxy 127.0.0.1:$KAIRA_PORT {
$token_line
    }
}
EOF
}

write_caddyfile "basic_auth"
if ! caddy validate --config "$CADDYFILE" >/dev/null 2>&1; then
    echo "==> 'basic_auth' rejected; falling back to the pre-2.8 'basicauth' spelling"
    write_caddyfile "basicauth"
    caddy validate --config "$CADDYFILE"
fi

systemctl enable --now caddy
systemctl reload caddy || systemctl restart caddy

# --- Verify (ACME can take a few seconds on the first request for each host) ---
echo "==> Waiting for certificates"
for host in "$NOVA_HOST" "$KAIRA_HOST"; do
    ok=""
    for _ in $(seq 1 20); do
        code=$(curl -fsS -o /dev/null -w '%{http_code}' --max-time 10 \
            -u "$WEB_USER:$WEB_PASSWORD" "https://$host/status" 2>/dev/null) || code=""
        if [ "$code" = "200" ]; then ok=1; break; fi
        sleep 3
    done
    if [ -n "$ok" ]; then
        echo "    OK   https://$host/status"
    else
        echo "    WARN https://$host/status not ready (is a bot listening on that port?)"
    fi
done

cat <<EOF
----------------------------------------------------------------
Open these on your phone (any network, cellular included):

  Nova    https://$NOVA_HOST/client/
  Kaira   https://$KAIRA_HOST/client/

  username: $WEB_USER
  password: $WEB_PASSWORD

Save the password — it is not stored anywhere in plaintext. To change it:
  WEB_PASSWORD=<new> bash tls-setup.sh

The native app is unaffected: it still talks plain HTTP to :$NOVA_PORT / :$KAIRA_PORT.
If the page loads and the mic works but the bot never connects, media (UDP) is being
blocked on that network — set TURN_TOKEN_ID / TURN_API_TOKEN in $ENV_FILE and restart
the containers to get a relay path.
  logs: docker logs -f voidai-bot   ·   caddy: journalctl -u caddy -f
----------------------------------------------------------------
EOF
